version: '3'
services:
  todofrontend:
    build: front-end/
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=todoback
    depends_on:
      - todoback
  todoback:
    build: back-end/
    ports:
      - 3001:3001
    environment:
      - FRONT_HOST=todofrontend
  todotests:
    build: tests/
    environment:
      - FRONT_HOST=todofrontend
    depends_on:
      - todofrontend
      - todoback

